const styles = {
  main: {
    margin: "-8px",
    padding: ".5rem",
    maxHeight: "100vh",
  },
  container: {
    maxWidth: 960,
    display: "flex",
    flex: "1 0",
    justifyContent: "flex-start",
    alignItems: "center",
    margin: "auto",
    flexDirection: "column",
  },
  row: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: ".25rem auto",
  },
  letterContainer: {
    height: "3rem",
    width: "3rem",
    border: "2px solid #d3d6da",
    borderColor: "#d3d6da",
    borderRadius: 6,
    margin: "0 .1rem",
    display: "flex",
    flex: "1 0",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "Roboto, sans-serif",
    fontSize: "1.5rem",
    textTransform: "uppercase",
    userSelect: "none",
  },
  letterCorrect: {
    backgroundColor: "#6aaa64",
    borderColor: "#6aaa64",
    color: "#fff",
  },
  letterPartial: {
    backgroundColor: "#c9b458",
    borderColor: "#c9b458",
    color: "#fff",
  },
  letterIncorrect: {
    backgroundColor: "#878a8c",
    borderColor: "#878a8c",
    color: "#fff",
  },
  keyboardContainer: {
    display: "flex",
    flex: "1 0",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    flexDirection: "column",
  },
  keyboardRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    margin: ".2rem auto",
  },
  keyboardButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "3rem",
    minWidth: "2.5rem",
    fontFamily: "Roboto, sans-serif",
    fontSize: "1.25rem",
    background: "#d3d6da",
    margin: "auto .1rem",
    borderRadius: 6,
    textTransform: "uppercase",
    padding: ".25rem .5rem ",
    cursor: "pointer",
    userSelect: "none",
  },
  attemptedLetters: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Roboto, sans-serif",
    fontSize: "1.5rem",
    flexGrow: "1",
    padding: ".5rem .75rem",
    height: "100%",
    minHeight: 50,
    textTransform: "uppercase",
    userSelect: "none",
  },
};

export { styles };
